# 3. Feature Engineering<a id='3_Feature Engineering'></a>

## Data Imports

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import zscore
import re
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [2]:
# Load dataset
df = pd.read_csv("Data//data.csv")

#_________ Data manipulation in data wrangling part
# Function to clean column names
def clean_column_names(col):
    col = col.replace(' (times)', '') # Remove ' (times)'
    col = col.replace(' (Yuan ¥)', '') # Remove ' (Yuan ??)'
    col = col.replace('?', '')  # Remove question marks
    col = col.strip()  # Remove leading and trailing spaces
    col = col.replace(' ', '_')  # Replace spaces with underscores
    col = col.replace('%', 'pct')  # Replace % with 'percent'
    col = col.replace('/', '_to_')  # Replace / with '_to_'
    col = col.replace('(', '')  # Remove opening parentheses
    col = col.replace(')', '')  # Remove closing parentheses
    col = re.sub(r'_([a-z])', lambda x: '_' + x.group(1).upper(), col) # Convert first letter after underscore to uppercase
    return col

# Apply the function to all column names
df.columns = [clean_column_names(col) for col in df.columns]

# Convert binary variables to categorical
binary_columns = ['Bankrupt', 'Net_Income_Flag', 'Liability-Assets_Flag']
df[binary_columns] = df[binary_columns].astype('category')

df.drop(columns = 'Net_Income_Flag', inplace=True)

## 3.1 Engineering on Numerical Features <a id='3.1_Engineering_on_Numerical_Features'></a>

### 3.1.1 Train-Test Split

To prevent data leakage, first perform a train-test split. In the case of severe target variable imbalance, use the stratify argument to ensure that each split maintains the same proportion of target variable classes as the original dataset.

In [3]:
X = df.drop(columns=['Bankrupt'])  # Features
y = df['Bankrupt']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=77, stratify=y)

print(y_train.value_counts()/len(y_train))
print(y_test.value_counts()/len(y_test))

Bankrupt
0    0.967735
1    0.032265
Name: count, dtype: float64
Bankrupt
0    0.967742
1    0.032258
Name: count, dtype: float64

### 3.1.2 Normalizing Numeric Features: Min-Max Normalization

In [4]:
# Separate numeric and categorical features
X_train_num = X_train.select_dtypes(include=['number'])
X_train_cat = X_train[['Liability-Assets_Flag']]
X_test_num = X_test.select_dtypes(include=['number'])
X_test_cat = X_test[['Liability-Assets_Flag']]

# Initialize the scaler and Fit scaler with training numeric features
scaler = MinMaxScaler()
scaler.fit(X_train_num)

# Transform the numerical features in both training and test sets
X_train_num_scaled = scaler.transform(X_train_num)
X_test_num_scaled = scaler.transform(X_test_num)

# Convert scaled numerical features back to DataFrame
X_train_num_scaled = pd.DataFrame(X_train_num_scaled, columns=X_train_num.columns, index=X_train.index)
X_test_num_scaled = pd.DataFrame(X_test_num_scaled, columns=X_test_num.columns, index=X_test.index)

# Combine scaled numerical features with the categorical features
X_train_scaled = pd.concat([X_train_num_scaled, X_train_cat], axis=1)
X_test_scaled = pd.concat([X_test_num_scaled, X_test_cat], axis=1)

### 3.1.3 New Features Generation

Although there are already 93 features, new features can be created and then selected through feature selection to identify the most useful ones. As observed in the EDA stage, profitability indicators such as ROA and stability indicators like Debt Ratio are expected to be useful for bankruptcy prediction. 

Additionally, if financial stability deteriorates while profitability remains low, the probability of bankruptcy is expected to be higher. Considering this, features created by dividing stability indicators by profitability indicators are likely to improve model performance. 

However, given the large number of possible combinations of profitability and stability indicators, it is impractical to consider every combination. Moreover, high correlation was observed among features within the same category. Therefore, a few key stability indicators will be used to create new features by dividing them by a representative profitability feature, ROAA_Before_Interest_And_Pct_After_Tax.

In [5]:
stability_features = [
    'Debt_Ratio_Pct', 
    'Borrowing_Dependency', 
    'Cash_To_Current_Liability', 
    'Fixed_Assets_To_Assets',
    'Current_Ratio',
    'Quick_Ratio',
    'Total_Debt_To_Total_Net_Worth',
    'Net_Worth_To_Assets',
    'Long-term_Fund_Suitability_Ratio_A',
    'Contingent_Liabilities_To_Net_Worth',
    'Operating_Funds_To_Liability',
    'Current_Liability_To_Assets',
    'Current_Liabilities_To_Liability',
    'Current_Liabilities_To_Equity',
    'Long-term_Liability_To_Current_Assets',
    'Retained_Earnings_To_Total_Assets',
    'Liability_To_Equity',
    'Degree_Of_Financial_Leverage_DFL'
]

profitability_feature = 'ROAA_Before_Interest_And_Pct_After_Tax'

# Generate New Features
for feature in stability_features:
    new_feature_name = f'{feature}_To_ROA'
    X_train_scaled[new_feature_name] = (X_train_scaled[feature]+0.1) / (X_train_scaled[profitability_feature]+0.1)
    X_test_scaled[new_feature_name] = (X_test_scaled[feature]+0.1) / (X_test_scaled[profitability_feature]+0.1)

X_train_scaled.head()

,ROAC_Before_Interest_And_Depreciation_Before_Interest,ROAA_Before_Interest_And_Pct_After_Tax,ROAB_Before_Interest_And_Depreciation_After_Tax,Operating_Gross_Margin,Realized_Sales_Gross_Margin,Operating_Profit_Rate,Pre-tax_Net_Interest_Rate,After-tax_Net_Interest_Rate,Non-industry_Income_And_Expenditure_To_Revenue,Continuous_Interest_Rate_After_Tax,...,Long-term_Fund_Suitability_Ratio_A_To_ROA,Contingent_Liabilities_To_Net_Worth_To_ROA,Operating_Funds_To_Liability_To_ROA,Current_Liability_To_Assets_To_ROA,Current_Liabilities_To_Liability_To_ROA,Current_Liabilities_To_Equity_To_ROA,Long-term_Liability_To_Current_Assets_To_ROA,Retained_Earnings_To_Total_Assets_To_ROA,Liability_To_Equity_To_ROA,Degree_Of_Financial_Leverage_DFL_To_ROA
2953,0.529177,0.631219,0.610117,0.603843,0.603713,0.998360,0.758862,0.809475,0.415942,0.748126,...,0.149059,0.146300,0.593624,0.292429,1.437772,0.589482,0.136758,1.382251,0.518146,0.173408
3256,0.491396,0.591441,0.573058,0.605666,0.605378,0.998331,0.758810,0.809454,0.415869,0.748107,...,0.153155,0.151680,0.649465,0.198296,1.037022,0.618102,0.144625,1.431032,0.544201,0.183394
5111,0.576464,0.698075,0.687926,0.631243,0.631243,0.998943,0.759060,0.809697,0.415693,0.748385,...,0.133667,0.131235,0.648158,0.166375,1.257260,0.535222,0.125302,1.248493,0.470599,0.158872
350,0.546483,0.652499,0.624371,0.611871,0.611994,0.998803,0.759311,0.809789,0.416352,0.748454,...,0.142799,0.144047,0.656053,0.175096,1.188949,0.567615,0.132891,1.351416,0.499236,0.168509
2291,0.476771,0.571437,0.549134,0.596391,0.596391,0.998278,0.758674,0.809328,0.415655,0.747941,...,0.157423,0.155987,0.638408,0.360232,1.504229,0.645885,0.148934,1.448505,0.568079,0.188836

In [6]:
# Rescale Features including newly generated features
X_train_num =  X_train_scaled.select_dtypes(include=['number'])
X_train_cat =  X_train_scaled[['Liability-Assets_Flag']]
X_test_num = X_test_scaled.select_dtypes(include=['number'])
X_test_cat = X_test_scaled[['Liability-Assets_Flag']]

# Initialize the scaler and Fit scaler with training numeric features
scaler = MinMaxScaler()
scaler.fit(X_train_num)

# Transform the numerical features in both training and test sets
X_train_num_scaled = scaler.transform(X_train_num)
X_test_num_scaled = scaler.transform(X_test_num)

# Convert scaled numerical features back to DataFrame
X_train_num_scaled = pd.DataFrame(X_train_num_scaled, columns=X_train_num.columns, index=X_train.index)
X_test_num_scaled = pd.DataFrame(X_test_num_scaled, columns=X_test_num.columns, index=X_test.index)

# Combine scaled numerical features with the categorical features
X_train_scaled = pd.concat([X_train_num_scaled, X_train_cat], axis=1)
X_test_scaled = pd.concat([X_test_num_scaled, X_test_cat], axis=1)

In [7]:
X_train_scaled.head()

,ROAC_Before_Interest_And_Depreciation_Before_Interest,ROAA_Before_Interest_And_Pct_After_Tax,ROAB_Before_Interest_And_Depreciation_After_Tax,Operating_Gross_Margin,Realized_Sales_Gross_Margin,Operating_Profit_Rate,Pre-tax_Net_Interest_Rate,After-tax_Net_Interest_Rate,Non-industry_Income_And_Expenditure_To_Revenue,Continuous_Interest_Rate_After_Tax,...,Contingent_Liabilities_To_Net_Worth_To_ROA,Operating_Funds_To_Liability_To_ROA,Current_Liability_To_Assets_To_ROA,Current_Liabilities_To_Liability_To_ROA,Current_Liabilities_To_Equity_To_ROA,Long-term_Liability_To_Current_Assets_To_ROA,Retained_Earnings_To_Total_Assets_To_ROA,Liability_To_Equity_To_ROA,Degree_Of_Financial_Leverage_DFL_To_ROA,Liability-Assets_Flag
2953,0.529177,0.631219,0.610117,0.603843,0.603713,0.998360,0.758862,0.809475,0.415942,0.748126,...,0.026405,0.120006,0.059233,0.118640,0.096955,0.029677,0.229646,0.091755,0.037642,0
3256,0.491396,0.591441,0.573058,0.605666,0.605378,0.998331,0.758810,0.809454,0.415869,0.748107,...,0.029186,0.135876,0.025469,0.081703,0.103748,0.034770,0.239929,0.098847,0.044107,0
5111,0.576464,0.698075,0.687926,0.631243,0.631243,0.998943,0.759060,0.809697,0.415693,0.748385,...,0.018619,0.135505,0.014020,0.102002,0.084075,0.022262,0.201448,0.078814,0.028231,0
350,0.546483,0.652499,0.624371,0.611871,0.611994,0.998803,0.759311,0.809789,0.416352,0.748454,...,0.025241,0.137749,0.017147,0.095706,0.091764,0.027174,0.223145,0.086609,0.034470,0
2291,0.476771,0.571437,0.549134,0.596391,0.596391,0.998278,0.758674,0.809328,0.415655,0.747941,...,0.031412,0.132734,0.083553,0.124765,0.110343,0.037559,0.243613,0.105346,0.047630,0